services:
  web:
    build: https://github.com/ivanegri/app_pncp.git#main
    ports:
      - "18123:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
  # Local DB service (Commented out for Remote DB usage)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=jupiter
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"

volumes:
  postgres_data:
