services:
  web:
    build: https://github.com/ivanegri/app_pncp.git#main
    ports:
      - "18123:5000"
    environment:
      - DB_USER=admin
      - DB_PASS=admin123
      - DB_HOST=216.22.5.204
      - DB_PORT=5432
      - DB_NAME=jupiter
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
      - ./credentials.json:/app/credentials.json:ro
  # Local DB service (Commented out for Remote DB usage)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=jupiter
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"

volumes:
  postgres_data:
